// <auto-generated />
using System;
using LCDPC.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LCDPC.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516233712_AddAuthTraceAndLogin")]
    partial class AddAuthTraceAndLogin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LCDPC.Domain.Entities.Users.ApiResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Endpoint", "Method")
                        .IsUnique();

                    b.ToTable("api_resources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            Code = "auth.register.start",
                            Description = "Endpoint para iniciar flujo de registro y emitir OTP",
                            Endpoint = "/api/v1/auth/register/start",
                            Method = "POST",
                            Name = "Iniciar registro de cliente"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            Code = "health.api.get",
                            Description = "Health endpoint del controlador API",
                            Endpoint = "/api/health",
                            Method = "GET",
                            Name = "Health API Controller"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            Code = "health.probe.get",
                            Description = "Health check de infraestructura",
                            Endpoint = "/health",
                            Method = "GET",
                            Name = "Health probe"
                        });
                });

            modelBuilder.Entity("LCDPC.Domain.Entities.Users.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IdentityDocument")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Rif")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WhatsAppPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityDocument")
                        .IsUnique();

                    b.HasIndex("Rif")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("LCDPC.Domain.Entities.Users.RegistrationFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("OtpAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OtpBlockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime>("OtpExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("registration_flows", (string)null);
                });

            modelBuilder.Entity("LCDPC.Domain.Entities.Users.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "cliente",
                            Description = "Rol cliente para operaciones comerciales",
                            Name = "cliente"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "admin_sede",
                            Description = "Administrador con alcance a sedes asignadas",
                            Name = "admin_sede"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "admin_global",
                            Description = "Administrador con alcance global",
                            Name = "admin_global"
                        });
                });

            modelBuilder.Entity("LCDPC.Domain.Entities.Users.RoleResourcePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanAll")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanView")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanWrite")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("RoleId", "ResourceId")
                        .IsUnique();

                    b.ToTable("role_resource_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            CanAll = false,
                            CanDelete = false,
                            CanUpdate = false,
                            CanView = false,
                            CanWrite = true,
                            CreatedAtUtc = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ResourceId = new Guid("44444444-4444-4444-4444-444444444441"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            CanAll = false,
                            CanDelete = false,
                            CanUpdate = false,
                            CanView = false,
                            CanWrite = true,
                            CreatedAtUtc = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ResourceId = new Guid("44444444-4444-4444-4444-444444444441"),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            CanAll = false,
                            CanDelete = false,
                            CanUpdate = false,
                            CanView = false,
                            CanWrite = true,
                            CreatedAtUtc = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ResourceId = new Guid("44444444-4444-4444-4444-444444444441"),
                            RoleId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555554"),
                            CanAll = false,
                            CanDelete = false,
                            CanUpdate = false,
                            CanView = true,
                            CanWrite = false,
                            CreatedAtUtc = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ResourceId = new Guid("44444444-4444-4444-4444-444444444442"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CanAll = false,
                            CanDelete = false,
                            CanUpdate = false,
                            CanView = true,
                            CanWrite = false,
                            CreatedAtUtc = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ResourceId = new Guid("44444444-4444-4444-4444-444444444442"),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555556"),
                            CanAll = false,
                            CanDelete = false,
                            CanUpdate = false,
                            CanView = true,
                            CanWrite = false,
                            CreatedAtUtc = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ResourceId = new Guid("44444444-4444-4444-4444-444444444442"),
                            RoleId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555557"),
                            CanAll = false,
                            CanDelete = false,
                            CanUpdate = false,
                            CanView = true,
                            CanWrite = false,
                            CreatedAtUtc = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ResourceId = new Guid("44444444-4444-4444-4444-444444444443"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555558"),
                            CanAll = false,
                            CanDelete = false,
                            CanUpdate = false,
                            CanView = true,
                            CanWrite = false,
                            CreatedAtUtc = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ResourceId = new Guid("44444444-4444-4444-4444-444444444443"),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555559"),
                            CanAll = false,
                            CanDelete = false,
                            CanUpdate = false,
                            CanView = true,
                            CanWrite = false,
                            CreatedAtUtc = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ResourceId = new Guid("44444444-4444-4444-4444-444444444443"),
                            RoleId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("LCDPC.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime?>("EmailVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OnboardingStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LCDPC.Domain.Entities.Users.UserRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("SedeIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId", "Active");

                    b.ToTable("user_role_assignments", (string)null);
                });

            modelBuilder.Entity("LCDPC.Domain.Entities.Users.Profile", b =>
                {
                    b.HasOne("LCDPC.Domain.Entities.Users.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("LCDPC.Domain.Entities.Users.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LCDPC.Domain.Entities.Users.RoleResourcePermission", b =>
                {
                    b.HasOne("LCDPC.Domain.Entities.Users.ApiResource", "Resource")
                        .WithMany("RolePermissions")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LCDPC.Domain.Entities.Users.Role", "Role")
                        .WithMany("ResourcePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LCDPC.Domain.Entities.Users.UserRoleAssignment", b =>
                {
                    b.HasOne("LCDPC.Domain.Entities.Users.Role", "Role")
                        .WithMany("Assignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LCDPC.Domain.Entities.Users.User", "User")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LCDPC.Domain.Entities.Users.ApiResource", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("LCDPC.Domain.Entities.Users.Role", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ResourcePermissions");
                });

            modelBuilder.Entity("LCDPC.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("Profile");

                    b.Navigation("RoleAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
